on:
  push:

jobs:
  test:
    name: "Test Migration Engine"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          default: true

      - run: cargo test
        working-directory: migration-engine/migration-engine-tests
