on:
  push:

jobs:

  compile:
    name: "Compile Migration Engine tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: migration-engine-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: timeout 40m cargo test --no-run
        working-directory: migration-engine/migration-engine-tests

  test:
    name: "Test Migration Engine - ${{ matrix.database }}"
    
    strategy:
      fail-fast: false
      matrix:
        database: [mssql_2017, mysql, mysql_5_6, mysql_8, mysql_mariadb, postgres, mssql_2019, postgres12, postgres11, postgres9, sqlite, postgres13, mssql_2017]
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Start databases"
        run: docker-compose up -d
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: migration-engine-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo test ${{ matrix.database }}
        working-directory: migration-engine/migration-engine-tests
